### ISSUE TITLE
Porting to other gym environments

### ISSUE THREAD

**Issue by kessler-frost** [hardmaru/WorldModelsExperiments#10]
I wanted to ask that in order to port this to other gym environments, where exactly should I make changes. Like, what should I modify in the `doomreal.py` file (this is where I believe most of the changes are required. Other files only require a bit of refactoring).

**Comment by hardmaru** [comment]
Hi @kessler-frost 

I'm not sure to be honest. The code is not that well written and as you can see even DoomRNN and CarRacing have different code bases. If I was a legit software engineer, both would be using the same code base :)

I think you might have a better idea than me for refactoring.

Best.

**Comment by kessler-frost** [comment]
Thanks :) will fiddle around with things to find that out then. Hopefully, will come up with a solution so that it becomes easier for future development 🤟.
