### ISSUE TITLE
the training of CMA-ES shows high average reward but when you just check the model against the log the rewards are practically zero

### ISSUE THREAD

**Issue by itabhiyanta** [hardmaru/WorldModelsExperiments#11]
Hi @hardmaru 

Thanks for posting this repo. i have a strange issue I see a very promising curve for the training of my CMA-ES model however i cannot replicate the results when i execute the following command.

python3.5 model.py log/filewiththe best stats.json
![dispatch](https://user-images.githubusercontent.com/8046022/50229883-a1c76100-03ab-11e9-826c-b1b7b65c493f.png)

I am using a custom environment.

I also wish to ask you something about the number of processors for the training of the CMA-ES model. I used 16 processors and also 48 processors (couldn't use 64 processors as then i run out of memory). Do you think reducing the number of processors for training of the CMA-ES model will have some adverse effect?

Kindly advise.
Rohit

**Comment by hardmaru** [comment]
Hi

You may have forgotten an extra flag (render/norender)

```
python model.py render log/carracing.cma.16.64.best.json
```

Chk out blog post
http://blog.otoro.net/2018/06/09/world-models-experiments/

**Comment by hardmaru** [comment]
cool. I'd be interested to see any results for custom environments, looking forward to see your publications in the future.
