### ISSUE TITLE
Memory leak and potential fix

### ISSUE THREAD

**Issue by davidsandberg** [hardmaru/WorldModelsExperiments#13]
Hi @hardmaru!
Thanks for a great repo and a really cool project!!
I was running the 'carracing' experiment but experienced memory problems. This was caused by new tensorflow assign operations being created every time set_model_params (in rnn.py and vae.py) is called. 
I implemented a fix where the assign operations were created when the graph was built and used when setting the parameters.
If you are interested in a fix I can make a PR, or you simply just copy and paste the fix from [here](https://github.com/davidsandberg/WorldModelsExperiments/compare/c31e8d84bcfdbebf12513ccdef9800d20477542d...e759ffc140925b324b6fac28f9e23cc1789709bc) (look at the diffs in rnn.py and vae.py).

**Comment by hardmaru** [comment]
Thanks for identifying the leak! Can you do a favor and create a PR?
