### ISSUE TITLE
cannot reshape array of size 51529 into shape (227,227,3)

### ISSUE THREAD

**Issue by Flamer17** [hardmaru/WorldModelsExperiments#15]
import matplotlib.pyplot as plt

test_data = process_test_data()
test_data = np.load('test_data.npy')

fig=plt.figure()

for num,data in enumerate(test_data[:12]):
   
    img_num = data[1]
    img_data = data[0].reshape(-1,IMG_SIZE,IMG_SIZE,3)
    
    y = fig.add_subplot(3,4,num+1)
    orig = img_data
    data = img_data
    model_out = model.predict([data])[0]
    
    if np.argmax(model_out) == 1: str_label='Dog'
    else: str_label='Cat'
        
    y.imshow(orig,cmap='gray')
    plt.title(str_label)
    y.axes.get_xaxis().set_visible(False)
    y.axes.get_yaxis().set_visible(False)
plt.show()

**Comment by hardmaru** [comment]
Hi,

Not sure I understand

What does the world models paper have to do with classifying dogs and cats?

Also where did you get 227x227x3 dimensions from? To my knowledge, this m
has nothing to do with the paper.

**Comment by Chazzz** [comment]
Flamer seems to be referencing code completely unrelated to the repo. I think this is safe to ignore.

Code is here: [https://gist.github.com/NgachaIan/28a86d9a78af1afdc344b373bd19e568](https://gist.github.com/NgachaIan/28a86d9a78af1afdc344b373bd19e568)
