### ISSUE TITLE
About the new version

### ISSUE THREAD

**Issue by marooncn** [hardmaru/WorldModelsExperiments#28]
Hi, Thanks for your work and I find some files were updated, such as [03_generate_rnn_data.py](https://github.com/AppliedDataSciencePartners/WorldModels/blob/master/03_generate_rnn_data.py) and [04_train_rnn.py ](https://github.com/AppliedDataSciencePartners/WorldModels/blob/master/04_train_rnn.py). Is it because the previous file has an error? (Because I ever used the files that has not updated to train my agent.) And I read the updated code and find they are almost the same except that RNN can predict reward now. Is it right?

**Comment by hardmaru** [comment]
Hi @marooncn 

The files in your links belong to another repo (https://github.com/AppliedDataSciencePartners) and they are not created by me. You should ask @AppliedDataSciencePartners about that repo and the files you are concerned about.

Best.
