### ISSUE TITLE
Ask for advice

### ISSUE THREAD

**Issue by marooncn** [hardmaru/WorldModelsExperiments#29]
Hi, thanks for your work. I have one problem to ask for your advice.
In these two experiments, the goal is included in the original image. But what if it is not included? I try to use World Model to solve the robot navigation  task. The state is {_image, relative_position_}, in which _image_ tells the robot to avoid obstacles and  _relative_position_ tells where the goal is. I use World Models to condense the captured image and MDN-RNN to remember the environment. Then  outputs of VAE and MDN-RNN are concatenated with _relative_position_ as controller's input. But the it can't work, then I try different structures of controller(I use DNN as controller), it still doesn't work. Any advice?
Details: The image is 64X48X3 and the latent dim of VAE is 32. The training result is good:
![vae_show](https://user-images.githubusercontent.com/29606478/59435925-3b367380-8e21-11e9-887d-2bbd5e914797.png)
The units in RNN is 256, the training result is also good:
![3](https://user-images.githubusercontent.com/29606478/59436479-450ca680-8e22-11e9-9c58-38fee6d8acc5.png)

**Comment by hardmaru** [comment]
I would suggest looking into papers that are better at learning representation of scenes. Have you seen this recent paper? https://arxiv.org/abs/1907.13052
